version: '3'

networks:
  repo-net:
    driver: bridge

volumes:
  nexus_data: {}

services:
  nexus:
    build: nexus
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    expose:
      - 5000
      - 8081
    ports:
      - 5000:5000
      - 8086:8081
    volumes:
      - nexus_data:/nexus-data
      - ./nexus/nexus.vmoptions:/nexus.vmoptions
    labels:
      role: "repository"
      environment: "test"
      app: "nexus"
    networks:
      - repo-net

  nginx:
    image: nginx:1.11
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    ports:
      - "8085:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "nginx -g 'daemon off;'"
    depends_on:
      - nexus
    restart: unless-stopped
    networks:
      - repo-net
    labels:
      role: "monitoring"
      environment: "test"
      app: "nginx"

