version: '2'

services:
  elasticsearch:
    #build: elasticsearch/
    image: elasticsearch:5
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
    volumes:
      - ./elasticsearch/data:/data
      - ./elasticsearch/conf/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    labels:
      PROJECT: "elk"
    networks:
      - docker_elk
  logstash:
    image: logstash:5
    hostname: logstash
    container_name: logstash
#    links:
#     - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
      - "8080:8080"
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    labels:
      PROJECT: "elk"
  kibana:
    image: kibana:5
    hostname: kibana
    container_name: kibana
#    links: 
#      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./kibana/config/:/etc/kibana/
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    labels:
      PROJECT: "elk"

networks:
  docker_elk:
    driver: bridge
