FROM  ubuntu:16.04
ENV   container docker

# Update system
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yqq \
    wget \
    curl \
    vim \
    dnsutils \
    python-pip \
    python-dev \
    python-apt \
    software-properties-common \
    dmidecode \
    apt-transport-https \
    systemd

# Install salt master/minion/cloud/api
RUN echo "deb http://repo.saltstack.com/apt/ubuntu/$(lsb_release -rs)/amd64/latest $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/saltstack.list && \
    wget -q -O- "https://repo.saltstack.com/apt/ubuntu/$(lsb_release -rs)/amd64/latest/SALTSTACK-GPG-KEY.pub" | apt-key add - && \
    DEBIAN_FRONTEND=noninteractive apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -yqq \
    salt-master \
    salt-minion \
    salt-cloud \
    salt-api \
    salt-ssh \
    salt-syndic && \
    pip install cherrypy docker-py halite

# Clean image
RUN apt-get -yqq clean && \
    apt-get -yqq purge && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /var/lib/apt/lists/*

# In order to gracefully stop systemd we need to set the stop signal to
# # SIGRTMIN+3 and set the container environment variable
STOPSIGNAL SIGRTMIN+3

# No need for graphical.target here
RUN systemctl set-default multi-user.target

# Expose volumes
VOLUME ["/etc/salt", "/var/cache/salt", "/var/logs/salt", "/srv"]

WORKDIR /srv/salt
EXPOSE 4505 4506 8080 8081
CMD [ "/sbin/init" ]
