version: '2'

services:
  rabbit1:
    image: "rabbitmq:3.6-management"
    hostname: "rabbit1"
    container_name: rabbit1
    ports:
    - "15671:15671"
    - "5671:5671"
    volumes:
      #- ./certs:/certs
      - ./conf/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
    labels:
      NAME: "rabbitmq1"
    networks:
      - my-network

networks:
  my-network:
    external: true
