version: '2'

services:
  elasticsearch:
    #build: elasticsearch/
    image: elasticsearch:2
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    volumes:
      - ./elasticsearch/:/elasticsearch
    labels:
      PROJECT: "elk"
    networks:
      - docker_elk
  logstash:
    image: logstash:2.4
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    command: logstash agent --debug -e 'input { log4j { mode => "server" port => "12201"} } output { elasticsearch { hosts => ["elasticsearch"] } stdout {} }'
    volumes:
      - ./logstash/:/logstash
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    labels:
      PROJECT: "elk"
  kibana:
    image: kibana:4.6
    links: 
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./kibana/config/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge
