version: '2'

services:
  moto:
    image: dnabic/moto:v0.1.1
    hostname: moto
    container_name: moto
    networks:
      -  moto_net
  moto:
    build: go/1.8
    hostname: dev-go
    container_name: dev-go
    networks:
      -  moto_net

networks:
  moto_net:
    driver: bridge
